name: Test OCI Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install OCI CLI
      run: sudo pip install oci-cli

    - name: Configure OCI CLI
      run: |
        mkdir -p ~/.oci
        echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        echo "[DEFAULT]" > ~/.oci/config
        echo "user=${{ secrets.OCI_USER }}" >> ~/.oci/config
        echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
        echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
        echo "tenancy=${{ secrets.OCI_TENANCY }}" >> ~/.oci/config
        echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
        chmod 600 ~/.oci/config
        oci setup repair-file-permissions --file ~/.oci/config

    - name: List OCI Compartments
      run: |
        export OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING=True
        oci iam compartment list --compartment-id ${{ secrets.OCI_TENANCY }} --all

    - name: Clean up
      run: rm -f ~/.oci/oci_api_key.pem
